from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views import View
from django.views.generic import TemplateView
from django.urls import reverse


# Create your views here.
def home(request):
    return HttpResponse("Hello Django!")


def about(request):
    return HttpResponse("About Page!")


def function_view(request):
    context = {
        "page_title": "Function-Based View",
        "page_heading": "Welcome to the Function-Based View",
        "page_content": "This is the content generated by the function-based view.",
    }
    return render(request, "bootswatch.html", context)


#class from which all class based views inherit
class BaseView(TemplateView):
    default_title = 'My Website'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.setdefault('title', self.default_title)
        return context

class ClassView(BaseView):
  template_name = 'bootswatch.html'

  def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      context.update({
          'title': 'Class-Based View',
          'page_heading': 'Welcome to the Class-Based View',
          'page_content': 'This is the content generated by the class-based view.',
      })
      return context

class ThemeView(BaseView):
    template_name = 'theme.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Add additional context data if needed
        return context

    def post(self, request, *args, **kwargs):
        theme = request.POST.get('theme')
        response = HttpResponseRedirect(reverse('theme'))
        response.set_cookie('theme', theme)
        return response
